/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Level } from "./components/level";
import { Color } from "@ionic/core";
export namespace Components {
    interface DzuAlert {
        "class": string;
        "isCloseable": boolean;
        /**
          * Severity of the alert
         */
        "level": Level;
        "size": string;
        /**
          * src for an icon, otherwise one is choosen arording to severity
         */
        "src": string;
    }
    interface DzuBcrumb {
        "active": boolean;
        "disabled": boolean;
        /**
          * Contains a URL or a URL fragment that the hyperlink points to. If this property is set, an anchor tag will be rendered.
         */
        "href": string | undefined;
    }
    interface DzuBcrumbs {
        "color": Color;
    }
    interface DzuBottomnav {
        "class": string;
    }
    interface DzuBottomnavItem {
        "active": boolean;
        "class": string;
        "href": string;
        "icon": string;
        "src": string;
    }
    interface DzuIcon {
        /**
          * src for an icon, otherwise one is choosen arording to severity
         */
        "color": string;
        "name": string;
        "size": number;
    }
}
declare global {
    interface HTMLDzuAlertElement extends Components.DzuAlert, HTMLStencilElement {
    }
    var HTMLDzuAlertElement: {
        prototype: HTMLDzuAlertElement;
        new (): HTMLDzuAlertElement;
    };
    interface HTMLDzuBcrumbElement extends Components.DzuBcrumb, HTMLStencilElement {
    }
    var HTMLDzuBcrumbElement: {
        prototype: HTMLDzuBcrumbElement;
        new (): HTMLDzuBcrumbElement;
    };
    interface HTMLDzuBcrumbsElement extends Components.DzuBcrumbs, HTMLStencilElement {
    }
    var HTMLDzuBcrumbsElement: {
        prototype: HTMLDzuBcrumbsElement;
        new (): HTMLDzuBcrumbsElement;
    };
    interface HTMLDzuBottomnavElement extends Components.DzuBottomnav, HTMLStencilElement {
    }
    var HTMLDzuBottomnavElement: {
        prototype: HTMLDzuBottomnavElement;
        new (): HTMLDzuBottomnavElement;
    };
    interface HTMLDzuBottomnavItemElement extends Components.DzuBottomnavItem, HTMLStencilElement {
    }
    var HTMLDzuBottomnavItemElement: {
        prototype: HTMLDzuBottomnavItemElement;
        new (): HTMLDzuBottomnavItemElement;
    };
    interface HTMLDzuIconElement extends Components.DzuIcon, HTMLStencilElement {
    }
    var HTMLDzuIconElement: {
        prototype: HTMLDzuIconElement;
        new (): HTMLDzuIconElement;
    };
    interface HTMLElementTagNameMap {
        "dzu-alert": HTMLDzuAlertElement;
        "dzu-bcrumb": HTMLDzuBcrumbElement;
        "dzu-bcrumbs": HTMLDzuBcrumbsElement;
        "dzu-bottomnav": HTMLDzuBottomnavElement;
        "dzu-bottomnav-item": HTMLDzuBottomnavItemElement;
        "dzu-icon": HTMLDzuIconElement;
    }
}
declare namespace LocalJSX {
    interface DzuAlert {
        "class"?: string;
        "isCloseable"?: boolean;
        /**
          * Severity of the alert
         */
        "level"?: Level;
        "onClosed"?: (event: CustomEvent<DzuAlert>) => void;
        "size"?: string;
        /**
          * src for an icon, otherwise one is choosen arording to severity
         */
        "src"?: string;
    }
    interface DzuBcrumb {
        "active"?: boolean;
        "disabled"?: boolean;
        /**
          * Contains a URL or a URL fragment that the hyperlink points to. If this property is set, an anchor tag will be rendered.
         */
        "href"?: string | undefined;
        /**
          * Emitted when the breadcrumb loses focus.
         */
        "onIonBlur"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the breadcrumb has focus.
         */
        "onIonFocus"?: (event: CustomEvent<void>) => void;
    }
    interface DzuBcrumbs {
        "color"?: Color;
    }
    interface DzuBottomnav {
        "class"?: string;
    }
    interface DzuBottomnavItem {
        "active"?: boolean;
        "class"?: string;
        "href"?: string;
        "icon"?: string;
        "src"?: string;
    }
    interface DzuIcon {
        /**
          * src for an icon, otherwise one is choosen arording to severity
         */
        "color"?: string;
        "name"?: string;
        "size"?: number;
    }
    interface IntrinsicElements {
        "dzu-alert": DzuAlert;
        "dzu-bcrumb": DzuBcrumb;
        "dzu-bcrumbs": DzuBcrumbs;
        "dzu-bottomnav": DzuBottomnav;
        "dzu-bottomnav-item": DzuBottomnavItem;
        "dzu-icon": DzuIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dzu-alert": LocalJSX.DzuAlert & JSXBase.HTMLAttributes<HTMLDzuAlertElement>;
            "dzu-bcrumb": LocalJSX.DzuBcrumb & JSXBase.HTMLAttributes<HTMLDzuBcrumbElement>;
            "dzu-bcrumbs": LocalJSX.DzuBcrumbs & JSXBase.HTMLAttributes<HTMLDzuBcrumbsElement>;
            "dzu-bottomnav": LocalJSX.DzuBottomnav & JSXBase.HTMLAttributes<HTMLDzuBottomnavElement>;
            "dzu-bottomnav-item": LocalJSX.DzuBottomnavItem & JSXBase.HTMLAttributes<HTMLDzuBottomnavItemElement>;
            "dzu-icon": LocalJSX.DzuIcon & JSXBase.HTMLAttributes<HTMLDzuIconElement>;
        }
    }
}
